name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cpp/**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cpp

    container:
      image: gcc:15.2.0

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: g++ -o a.out main.cpp
    - name: run
      run: ./a.out < input.in
